name = "GMMParameterEstimation"
uuid = "7a1c707a-4b3e-4a1f-9208-da91076bfd6f"
authors = ["Haley Colgate Kottler", "Julia Lindberg", "Jose Israel Rodriguez"]
version = "0.1.2"

[compat]
julia = "1.7"
HomotopyContinuation = "2.6.4"
Distributions = "0.25.62"
Combinatorics = "1.0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
