name = "GMPE"
uuid = "7a1c707a-4b3e-4a1f-9208-da91076bfd6f"
authors = ["Haley Colgate Kottler", "Julia Lindberg", "and Jose Israel Rodriguez"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
